# Generated by Django 4.0.2 on 2022-04-20 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DefaultProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=1200, verbose_name='Описание')),
                ('weight', models.IntegerField(blank=True, verbose_name='Вес')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Список товаров',
            },
        ),
        migrations.CreateModel(
            name='Dops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Дополнение',
                'verbose_name_plural': 'Допы',
            },
        ),
        migrations.CreateModel(
            name='Masterclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Открыт для записи', 'Открыт для записи'), ('Завершенный', 'Завершенный')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(blank=True, default='', upload_to='media/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(blank=True, default='', max_length=250, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес')),
                ('price', models.IntegerField(verbose_name='Сумма')),
                ('bonusesused', models.IntegerField(blank=True, default=0, verbose_name='Бонусов использовано')),
                ('bonusesadded', models.IntegerField(blank=True, default=0, verbose_name='Бонусов начислено')),
                ('promocodesale', models.IntegerField(blank=True, default=0, verbose_name='Скидка %')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='Номер телефона клиента:')),
                ('created', models.TimeField(default=django.utils.timezone.now, verbose_name='Заказ был создан в:')),
                ('pay_method', models.CharField(choices=[('Онлайн оплата', 'Онлайн оплата'), ('Наличные', 'Наличные')], default='На доставку', max_length=255, verbose_name='Способ оплаты:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('status', models.CharField(choices=[('На доставку', 'На доставку'), ('Самовывоз', 'Самовывоз')], max_length=100, verbose_name='Доставка/Самовывоз')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.TextField(verbose_name='Состав/Выход')),
                ('size', models.CharField(default='25', max_length=100, verbose_name='Размер')),
                ('weight', models.IntegerField(blank=True, default=0, verbose_name='Вес')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Цена')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Изображение')),
                ('dops', models.ManyToManyField(to='main.Dops', verbose_name='Допы в карточке товара')),
                ('dopscart', models.ManyToManyField(to='main.DefaultProduct', verbose_name='Допы для корзины, если там этот товар')),
            ],
            options={
                'verbose_name': 'Вариация',
                'verbose_name_plural': 'Вариации',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('hit', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Список Пиццы',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sale', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=500, verbose_name='улица')),
                ('house', models.CharField(default='1', max_length=250, verbose_name='Дом')),
                ('open', models.TimeField(default=django.utils.timezone.now, verbose_name='Открывается в:')),
                ('close', models.TimeField(default=django.utils.timezone.now, verbose_name='Закрывается в:')),
                ('minimalorder', models.IntegerField(default=0, verbose_name='Сумма миннимального заказа:')),
                ('zone', models.FileField(default='settings.MEDIA_ROOT/kml/default.kml', upload_to='kml/', verbose_name='Зоны доставки(в формате KML)')),
            ],
            options={
                'verbose_name': 'Натройки пиццерии',
                'verbose_name_plural': 'Натройки пиццерий',
            },
        ),
        migrations.CreateModel(
            name='UserLoggined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=200, verbose_name='Устройство')),
                ('loggined', models.BooleanField(default=False, verbose_name='Авторизован')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Номер телефона')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('birthday', models.CharField(blank=True, default='', max_length=255, verbose_name='День рождения')),
                ('street', models.CharField(blank=True, default='', max_length=255, verbose_name='Улиц')),
                ('house', models.CharField(blank=True, default='', max_length=255, verbose_name='Дом')),
                ('apartament', models.CharField(blank=True, default='', max_length=255, verbose_name='Квартира')),
                ('enter', models.CharField(blank=True, default='', max_length=255, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, default='', max_length=255, verbose_name='Этаж')),
                ('code', models.CharField(blank=True, default='', max_length=255, verbose_name='Код')),
                ('address_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название адреса')),
                ('address_comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('pickup', models.CharField(blank=True, default='', max_length=255, verbose_name='Самовывоз')),
                ('delivery_choice', models.BooleanField(blank=True, default=True, verbose_name='Выбор доставки')),
                ('bonuses', models.IntegerField(blank=True, default=0, verbose_name='Бонусы')),
                ('qr', models.ImageField(blank=True, upload_to='media/', verbose_name='QR Code, данное поле не для заполнения ')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='UserStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PromocodeToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode', to='main.userloggined')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='ProductToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.userloggined')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукт в корзине')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='main.productgroup', verbose_name='Группа товаров'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.order')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар в заказе')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.shop', verbose_name='Заказ отправлен в ресторан'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.userloggined', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='MasterclassOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('masterclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='DopToProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dops')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dops', to='main.orderproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DopToProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dops')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dops', to='main.producttocart')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultProductToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_prod', to='main.userloggined')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.defaultproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentation', models.TextField()),
                ('raiting_one', models.IntegerField(blank=True, default=5)),
                ('raiting_two', models.IntegerField(blank=True, default=5)),
                ('raiting_three', models.IntegerField(blank=True, default=5)),
                ('raiting_four', models.IntegerField(blank=True, default=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentation', to='main.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=250)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('house', models.CharField(blank=True, max_length=100)),
                ('entrance', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
