# Generated by Django 4.0.2 on 2022-04-20 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doptoproductorder',
            options={'verbose_name': 'Допы к товару в заказе', 'verbose_name_plural': 'Допы к товару в заказе'},
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(to='main.Shop', verbose_name='Пиццерии'),
        ),
        migrations.AlterField(
            model_name='doptoproductorder',
            name='dop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dops', verbose_name='Дополнение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заказ был создан в:'),
        ),
    ]
