# Generated by Django 4.0.2 on 2022-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_defaultproduct_dops_defaultproduct_dopscart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultproduct',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='defaultproduct',
            name='composition',
            field=models.TextField(default='', verbose_name='Состав/Выход'),
        ),
        migrations.AddField(
            model_name='defaultproduct',
            name='hit',
            field=models.BooleanField(default=False, verbose_name='Хит'),
        ),
        migrations.AddField(
            model_name='defaultproduct',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
    ]
