# Generated by Django 4.0.2 on 2022-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_defaultproduct_active_defaultproduct_composition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('dopscart', models.ManyToManyField(to='main.DefaultProduct', verbose_name='Подарок')),
            ],
            options={
                'verbose_name': 'Подарок от суммы заказа',
                'verbose_name_plural': 'Подарки от суммы заказа',
            },
        ),
    ]
