# Generated by Django 4.0.2 on 2022-04-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_presentprice_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultproduct',
            name='dops',
            field=models.ManyToManyField(blank=True, to='main.Dops', verbose_name='Допы в карточке товара'),
        ),
        migrations.AlterField(
            model_name='defaultproduct',
            name='dopscart',
            field=models.ManyToManyField(blank=True, to='main.DefaultProduct', verbose_name='Допы для корзины, если там этот товар'),
        ),
        migrations.AlterField(
            model_name='defaultproduct',
            name='shops',
            field=models.ManyToManyField(blank=True, to='main.Shop', verbose_name='Пиццерии'),
        ),
    ]
