# Generated by Django 4.0.2 on 2022-04-26 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_defaultproduct_dops_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Наcтройки пиццерии', 'verbose_name_plural': 'Наcтройки пиццерий'},
        ),
        migrations.AddField(
            model_name='defaultproduct',
            name='marker',
            field=models.CharField(choices=[(' ', ' '), ('Острая', 'Острая'), ('Сладкая', 'Сладкая')], default='Сладкая', max_length=255, verbose_name='Острая и Сладкая:'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='marker',
            field=models.CharField(choices=[('', ''), ('Острая', 'Острая'), ('Сладкая', 'Сладкая')], default='Сладкая', max_length=255, verbose_name='Острая и Сладкая:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='close2',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Вторник Закрывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='close3',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Среда Закрывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='close4',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Четверг Закрывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='close5',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Пятница Закрывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='close6',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Суббота Закрывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='close7',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Воскресенье Закрывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='globalmail',
            field=models.CharField(default='', max_length=255, verbose_name='Почта для дублирования уведомлений:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='mailsend',
            field=models.CharField(default='', max_length=255, verbose_name='Почта для уведомлений :'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open2',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Вторник Открывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open3',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Среда Открывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open4',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Четверг Открывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open5',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Пятница Открывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open6',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Суббота Открывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open7',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Воскресенье Открывается в:'),
        ),
        migrations.AddField(
            model_name='shop',
            name='saleon',
            field=models.IntegerField(default=0, verbose_name='Скидка на вынос %:'),
        ),
        migrations.AlterField(
            model_name='presentprice',
            name='price',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='sale',
            field=models.IntegerField(verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='close',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Понедельник Закрывается в:'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Понедельник Открывается в:'),
        ),
    ]
