# Generated by Django 4.0.2 on 2022-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_shop_options_defaultproduct_marker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название адреса'),
        ),
        migrations.AddField(
            model_name='order',
            name='apartament',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_choice',
            field=models.BooleanField(blank=True, default=True, verbose_name='Выбор доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='enter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Самовывоз'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Улиц'),
        ),
    ]
