# Generated by Django 4.0.2 on 2022-05-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_address_order_address_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('Онлайн оплата', 'Онлайн оплата'), ('Наличные', 'Наличные')], default='Наличные', max_length=255, verbose_name='Способ оплаты:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('На доставку', 'На доставку'), ('Самовывоз', 'Самовывоз')], default='На доставку', max_length=100, verbose_name='Доставка/Самовывоз'),
        ),
        migrations.CreateModel(
            name='OrderProductDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsdefault', to='main.order')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.defaultproduct', verbose_name='Товар в заказе')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='DopToProductDefaultOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dops', verbose_name='Дополнение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dops', to='main.orderproductdefault')),
            ],
            options={
                'verbose_name': 'Допы к товару в заказе',
                'verbose_name_plural': 'Допы к товару в заказе',
            },
        ),
        migrations.CreateModel(
            name='DopToDefaultProductToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dops')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dops', to='main.defaultproducttocart')),
            ],
        ),
    ]
