# Generated by Django 4.0.2 on 2022-05-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orderproduct_count_alter_order_pay_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст(<h1>Заголовок</h1>)')),
            ],
            options={
                'verbose_name': 'Страница "О приложении"',
                'verbose_name_plural': 'Страница "О приложении"',
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст(<h1>Заголовок</h1>)')),
            ],
            options={
                'verbose_name': 'Страница "Правовые документы"',
                'verbose_name_plural': 'Страница "Правовые документы"',
            },
        ),
        migrations.AlterField(
            model_name='producttocart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tocart', to='main.product', verbose_name='Продукт в корзине'),
        ),
    ]
