# Generated by Django 4.0.2 on 2022-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutpage_policypage_alter_producttocart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloggined',
            name='email',
            field=models.CharField(default='', max_length=300, verbose_name=''),
        ),
        migrations.AddField(
            model_name='userloggined',
            name='push',
            field=models.BooleanField(default=True, verbose_name='Push уведомления'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
